"""empty message

Revision ID: 3db9511543ff
Revises: 
Create Date: 2020-10-18 22:16:20.183437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db9511543ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humidity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.Integer(), nullable=True),
    sa.Column('inside', sa.Float(), nullable=True),
    sa.Column('outside', sa.Float(), nullable=True),
    sa.Column('dif', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt', sa.Integer(), nullable=True),
    sa.Column('inside', sa.Float(), nullable=True),
    sa.Column('outside', sa.Float(), nullable=True),
    sa.Column('dif', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature')
    op.drop_table('humidity')
    # ### end Alembic commands ###
